### ISSUE TITLE
Could you possibly provide us an requirement.txt?

### ISSUE THREAD

**Issue by SuAnita520** [semitable/seac#2] opened 2021-04-13 12:58 UTC
I couldn't run this repo, since I got 

`ImportError: cannot import name 'QueuedMongoObserver'`
My current python is 3.6,  and sacred is 0.7.2

**Comment by semitable** [comment] 2021-04-15 15:24
Hi,
A requirements.txt has been added. I can confirm that a Python 3.8 installation with sacred 0.8.2 (latest) works fine. I am not sure whether your problem will be resolved with this. Currently, the code is set tup to use a FileStorageObserver (more info about sacred observers can be found here: https://sacred.readthedocs.io/en/stable/observers.html).

Installation of the robotic_warehouse and lb-foraging environments (links in README) might still be required. Note that both repositories might have been updated/changed so gym versions might need to be increased (e.g. "env_name=Foraging-15x15-3p-4f-v1" instead of v0.)

Also, since these environments are optional, they can be commented out (if not needed) from the files and replaced with other environment packages.

**Closed as completed by semitable** 2021-04-15 15:24 UTC
